export const GET_INGREDIENTS = 'GET_INGREDIENTS'
export const GET_INGREDIENTS_FAILED = 'GET_INGREDIENTS_FILED'
export const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS'

export const SET_INGREDIENT_DETAILS = 'SET_INGREDIENT_DETAILS'
export const CLOSE_INGREDIENT_DETAILS =  'CLOSE_INGREDIENT_DETAILS'

export const SET_ORDER_DETAILS = 'SET_ORDER_DETAILS'
export const SET_ORDER_DETAILS_FAILED = 'SET_ORDER_DETAILS_FAILED'
export const SET_ORDER_DETAILS_SUCCESS = 'SET_ORDER_DETAILS_SUCCESS'

export const CLOSE_ORDER_DETAILS = 'CLOSE_ORDER_DETAILS'
export const SET_ORDERS_ID = 'SET_ORDERS_ID'

export const SET_CONSTRUCTOR_INGREDIENT = 'SET_CONSTRUCTOR_INGREDIENT'
export const MOVE_CONSTRUCTOR_INGREDIENT = 'MOVE_CONSTRUCTOR_INGREDIENT'
export const DELETE_CONSTRUCTOR_INGREDIENT = 'DELETE_CONSTRUCTOR_INGREDIENT'

export const SET_REGISTER_FORM_VALUE = 'SET_REGISTER_FORM_VALUE'
export const RESET_REGISTER_FORM = 'RESET_REGISTER_FORM'

export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'

export const GET_USER_DATA = 'GET_USER_DATA'