export const GET_INGREDIENTS = 'GET_INGREDIENTS'
export const GET_INGREDIENTS_FAILED = 'GET_INGREDIENTS_FILED'
export const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS'

export const SET_INGREDIENT_DETAILS = 'SET_INGREDIENT_DETAILS'
export const OPEN_INGREDIENT_DETAILS = 'OPEN_INGREDIENT_DETAILS'
export const CLOSE_INGREDIENT_DETAILS =  'CLOSE_INGREDIENT_DETAILS'

export const SET_ORDER_DETAILS = 'SET_ORDER_DETAILS'
export const SET_ORDER_DETAILS_FAILED = 'SET_ORDER_DETAILS_FAILED'
export const SET_ORDER_DETAILS_SUCCESS = 'SET_ORDER_DETAILS_SUCCESS'
export const CLOSE_ORDER_DETAILS = 'CLOSE_ORDER_DETAILS'

export const SET_ORDERS_ID = 'SET_ORDERS_ID'