const GET_INGREDIENTS = 'GET_INGREDIENTS'
const GET_INGREDIENTS_FAILED = 'GET_INGREDIENTS_FILED'
const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS'

export {
  GET_INGREDIENTS,
  GET_INGREDIENTS_FAILED,
  GET_INGREDIENTS_SUCCESS
}